### ISSUE TITLE
java.nio.BufferOverflowException

### ISSUE THREAD

**Issue by oluwabajio** [dbof10/Bitmp4#3]
Hello, i tried running your sample on my phone and it crashes with the below error

2021-02-25 02:20:04.190 14686-14686/? E/h.bitmp4.sampl: Unknown bits set in runtime_flags: 0x8000
2021-02-25 02:20:08.123 14686-14756/com.ctech.bitmp4.sample E/ion: ioctl c0044901 failed with code -1: Invalid argument
2021-02-25 02:20:08.123 14686-14756/com.ctech.bitmp4.sample E/C2AllocatorIon: >>>SEC C2AllocatorIon::mapUsage ion_is_legacy++++++++
2021-02-25 02:20:08.123 14686-14756/com.ctech.bitmp4.sample E/C2AllocatorIon: >>>SEC mapUsage	0, 2000000
2021-02-25 02:20:08.321 14686-14761/com.ctech.bitmp4.sample E/AndroidRuntime: FATAL EXCEPTION: EncodeThread
    Process: com.ctech.bitmp4.sample, PID: 14686
    java.nio.BufferOverflowException
        at java.nio.DirectByteBuffer.put(DirectByteBuffer.java:298)
        at java.nio.ByteBuffer.put(ByteBuffer.java:732)
        at com.ctech.bitmp4.MP4Encoder.onAddFrame(MP4Encoder.java:138)
        at com.ctech.bitmp4.Encoder$1.run(Encoder.java:40)
        at java.lang.Thread.run(Thread.java:919)

![bitmap4 error](https://user-images.githubusercontent.com/13810874/109088846-74f00080-7710-11eb-9274-e5374d3a04b4.PNG)

**Comment by dbof10** [comment]
this code doesn't not work on all android devices due to different native implementation. it works well on samsung device. you can fork and play around. contribute to the project is welcome

**Comment by dbof10** [comment]
fixed please pull latest

**Comment by Mouadabdelghafouraitali** [comment]
I'm facing the same issue here (Android 11 | POCO X3)

**Comment by javadVatan** [comment]
I got this error on version 0.1.1
<img width="1162" alt="image" src="https://user-images.githubusercontent.com/20107247/206922460-52c383bf-54d8-4e45-9946-820e5a35a952.png">
