### ISSUE TITLE
Export and Stop buttons not working

### ISSUE THREAD

**Issue by HeroSony** [dbof10/Bitmp4#4]
When I press Export button it produces the below error:
```
E/C2AllocatorIon: >>>SEC mapUsage Mapper1 1
E/ion: ioctl c0044901 failed with code -1: Not a typewriter
E/C2AllocatorIon: >>>SEC mapUsage	0, 1
E/AndroidRuntime: FATAL EXCEPTION: EncodeThread
    Process: com.ctech.bitmp4.sample, PID: 16545
    java.nio.BufferOverflowException
        at java.nio.DirectByteBuffer.put(DirectByteBuffer.java:298)
        at java.nio.ByteBuffer.put(ByteBuffer.java:732)
        at com.ctech.bitmp4.MP4Encoder.onAddFrame(MP4Encoder.java:138)
        at com.ctech.bitmp4.Encoder$1.run(Encoder.java:40)
        at java.lang.Thread.run(Thread.java:919)
```

When I press Stop button it produces the below error:
```
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.ctech.bitmp4.sample, PID: 16924
    kotlin.UninitializedPropertyAccessException: lateinit property exportDisposable has not been initialized
        at com.ctech.bitmp4.sample.MainActivity.stopExport(MainActivity.kt:113)
        at com.ctech.bitmp4.sample.MainActivity.access$stopExport(MainActivity.kt:24)
        at com.ctech.bitmp4.sample.MainActivity$onCreate$2.onClick(MainActivity.kt:83)
        at android.view.View.performClick(View.java:7862)
        at android.widget.TextView.performClick(TextView.java:15004)
        at android.view.View.performClickInternal(View.java:7831)
        at android.view.View.access$3600(View.java:879)
        at android.view.View$PerformClick.run(View.java:29359)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:237)
        at android.app.ActivityThread.main(ActivityThread.java:8167)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)
```

**Comment by dbof10** [comment]
you should click start export before click stop export

**Comment by HeroSony** [comment]
Both start export or stop export, it all does not work.

https://user-images.githubusercontent.com/4160246/109098942-cd48f180-7754-11eb-9ac5-8a7af44613e7.mp4

**Comment by dbof10** [comment]
fixed. please pull the latest
