### ISSUE TITLE
FATAL EXCEPTION: EncodeThread

### ISSUE THREAD

**Issue by R2D2RU** [dbof10/Bitmp4#8]
When using the library I get the exception:

2022-06-20 14:55:08.688 28013-28522/xxxxxxxxxx E/AndroidRuntime: FATAL EXCEPTION: EncodeThread
    Process: com.xxxxxxxxx, PID: 28013
    java.nio.BufferOverflowException
        at java.nio.DirectByteBuffer.put(DirectByteBuffer.java:298)
        at java.nio.ByteBuffer.put(ByteBuffer.java:732)
        at com.ctech.bitmp4.MP4Encoder.onAddFrame(MP4Encoder.java:138)
        at com.ctech.bitmp4.Encoder$1.run(Encoder.java:40)
        at java.lang.Thread.run(Thread.java:920)

Code:
Init:
      file = new File(SportUpApplication.getAppContext().getExternalFilesDir(null), "export.mp4");
      mp4Encoder=new MP4Encoder();
      mp4Encoder.setFrameDelay(20);
      mp4Encoder.setOutputFilePath(file.getPath());
      mp4Encoder.setOutputSize(640, 360);
      mp4Encoder.startEncode();

Loop:
     .....
       bitmap=Bitmap.createScaledBitmap(bitmap, 640, 360, true);
       mp4Encoder.addFrame(bitmap);
     .....

End:
    mp4Encoder.stopEncode();

What am I doing wrong?

**Comment by R2D2RU** [comment]
Your example throws a similar error:
2022-06-20 15:16:08.480 10578-10654/com.ctech.bitmp4.sample E/ion: ioctl c0044901 failed with code -1: Inappropriate ioctl for device
2022-06-20 15:16:08.481 10578-10654/com.ctech.bitmp4.sample I/CCodecBufferChannel: [c2.android.aac.encoder#875] 4 initial input buffers available
2022-06-20 15:16:08.485 10578-10578/com.ctech.bitmp4.sample D/MPEG4Writer: PreAllocation disabled. fallocate : Operation not supported on transport endpoint, 95
2022-06-20 15:16:08.547 10578-10660/com.ctech.bitmp4.sample E/AndroidRuntime: FATAL EXCEPTION: EncodeThread
    Process: com.ctech.bitmp4.sample, PID: 10578
    java.nio.BufferOverflowException
        at java.nio.DirectByteBuffer.put(DirectByteBuffer.java:298)
        at java.nio.ByteBuffer.put(ByteBuffer.java:732)
        at com.ctech.bitmp4.MP4Encoder.onAddFrame(MP4Encoder.java:138)
        at com.ctech.bitmp4.Encoder$1.run(Encoder.java:40)
        at java.lang.Thread.run(Thread.java:920)
2022-06-20 15:16:08.581 10578-10578/com.ctech.bitmp4.sample I/ViewRootImpl@c12097e[MainActivity]: MSG_WINDOW_FOCUS_CHANGED 0 1

**Comment by dbof10** [comment]
it was new android issue that app can't write to external file. you can try pull the latest again
